### ISSUE TITLE
大佬问一下引入.module.less会自动使用模块化css 这个逻辑是cra默认提供的吗

### ISSUE THREAD

**Issue by lie5860** [qjp88995/cra-template-qjp-typescript#1]

**Comment by qjp88995** [comment]
不是，是 [craco-less](https://github.com/DocSpring/craco-less) 提供的，cra 默认提供 css 和 sass
![image](https://user-images.githubusercontent.com/21209765/189389154-4ea6d652-7a08-45f9-8ca3-6aafcdf14426.png)

**Comment by lie5860** [comment]
谢谢大佬
